name: Deploy to VPS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Composer Dependencies
        run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

      - name: Install NPM Dependencies
        run: npm install

      - name: Build NPM Assets
        run: npm run build

      - name: Synchronize Files To Server
        uses: easingthemes/ssh-deploy@v2.1.7
        env:
          SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.VPS_USER }}
          REMOTE_HOST: ${{ secrets.VPS_HOST }}
          REMOTE_PORT: ${{ secrets.VPS_PORT }}
          SOURCE: "./"
          TARGET: "/public_html/powercool.at-easese.com"
          DEBUG: true
          
      - name: Run Remote/Artisan Commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
                cd /public_html/powercool.at-easese.com
                php artisan migrate --force
                php artisan optimize:clear
                php artisan optimize
